### ISSUE TITLE
XiaoMi-Pro GTX BIOS

### ISSUE THREAD

**Issue by ArvinZJC** [daliansky/XiaoMi-Pro-Hackintosh#194]
Could you get an updated version of XiaoMi-Pro BIOS that is compatible with the GTX version?

**Comment by stevezhengshiqi** [comment]
I will try. Maybe a few days later I will go to XiaoMi after-sale. It's so hard to get an updated BIOS version in my province. The local XiaoMi after-sale database is out-of-date.

**Comment by andy7z** [comment]
[XiaomiProGtxBiosFile.zip](https://github.com/daliansky/XiaoMi-Pro/files/3257108/XiaomiProGtxBiosFile.zip)
Hello, this is the XiaoMi Pro GTX's BIOS files, the version is **XMAKB5RRP0905**. 
It may can help you.
(By the way, the bios is locked, and the PchSetup offset 0x17 is 01.)

**Comment by ArvinZJC** [comment]
OK, that's cool! THX!

**Comment by andy7z** [comment]
Hello, how is it?

**Comment by ArvinZJC** [comment]
> Hello, how is it?

Till now, everything's okay.

**Comment by rjcrowder** [comment]
I can't seem to install the 905 bios because the bios is "locked". I have a bootable UEFI USB where I can send commands (that I copied from one of the Notebook MX bios installs). However, the "unlockme.nsh" doesn't seem to do anything, and flash.nsh reports that the bios is locked. Hoping you could tell me how to unlock it?

**Comment by killyungkim** [comment]
I have the 905 bios installed by default on my gtx version, but the voltages in XTU seem to be locked and any changes made in ThrottleStop get ignored by the system. Would it brick my laptop if i applied the 502 and 603 voltage patch posted in this thread https://www.reddit.com/r/Xiaomi/comments/93v6q6/mi_notebook_pro_bios_patcher_for_0502_and_0603/ ? A couple people asking there if anyone tried, to no avail. I've read some chatter about the 906 version being susceptible to 'an earlier existing patch' which might suggest that it could work.

**Comment by stevezhengshiqi** [comment]
@killyungkim Yes, the scripts you mentioned in that link will break GTX devices. It can only work in MX150 of any BIOS version.

**Comment by miloserdev** [comment]
> [XiaomiProGtxBiosFile.zip](https://github.com/daliansky/XiaoMi-Pro/files/3257108/XiaomiProGtxBiosFile.zip)
> Hello, this is the XiaoMi Pro GTX's BIOS files, the version is **XMAKB5RRP0905**.
> It may can help you.
> (By the way, the bios is locked, and the PchSetup offset 0x17 is 01.)

Hello, i have a problem with BIOS flashing.
I flash this with MX150 firmware and i don`t know how to go back.
If you can please help me.

**Comment by miloserdev** [comment]
Hello again.

Finally i solved the problem with Mi Notebook Pro GTX 1050 updated to MX150/MX250 BIOS and solution is here.
If you flashed your Pro GTX with XMAKB5R0P0*** (XMAKB5R0P0A07, XMAKB5R0P0E07, XMAKB5R0P0300, XMAKB5R0P0401, XMAKB5R0P0502, XMAKB5R0P0603, XMAKB5R0P0906) versions of Pro MX150/MX250 firmware do this things to unbrick your laptop
1. Download [XMAKB5RRP0804.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/5720597/XMAKB5RRP0804.zip) and unzip.
2. Open platform.ini and find Platform_Check then change Flag=1 to Flag=0
![image](https://user-images.githubusercontent.com/37951044/102706465-2868ee80-42a3-11eb-95ab-0bdf469f2632.png)
(This option needed because now your Pro GTX think he is Pro MX150/MX250 version)
3. Plug in the power and don't unplug!
4. Run H2OFFT-Wx64.exe as administrator.
Your laptop will be restart several times and finnaly the BIOS will be updated to XMAKB5RRP0(XMAKB5RRP0804
