### ISSUE TITLE
Touchpad issue on MiBook GTX

### ISSUE THREAD

**Issue by Violettx** [daliansky/XiaoMi-Pro-Hackintosh#223]
I'm using xiaomi EFI v1.3.5 replacing v1.3.4 on Catalina developer beta (19A512f) for my MiBook GTX i7 16G version. While I find that my touchpad isn't working for EFI v1.3.5. 
I've already replaced the SSDT-LGPAGTX.aml. Also I tried to fix the touchpad issue in three ways: use the touchpad on Windows for like 10 minutes then go to macOS, use KextUtiliy.app to fix and use "sudo kextcache -i /" to fix. None of them helped. 
Now I've returned to v1.3.4 and everything seems to be fine right now. I'm not sure is it an occasional issue or a bug. Maybe I'll try it a few days later cause I'm kinda busy right now. 
For my EFI updating, I replaced the config.plist from the old clover to the new one and then replace the clover and the boot folder to the EFI. It worked for the last few times. I'm not sure it's the right way to update the EFI so I write it here for your reference.

**Comment by stevezhengshiqi** [comment]
@Violettx Hi, please remember whenever you update EFI folder, please replace completely. You need to replace every file including config.plist!!! If you want to save your theme setting and serial numbers, please run bash -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/master/install.sh)" in Terminal.app

This issue will be closed since it’s user own problem.
