### ISSUE TITLE
How Can i disable discrete gpu? Thanks

### ISSUE THREAD

**Issue by HackDark00** [daliansky/XiaoMi-Pro-Hackintosh#226]

**Comment by stevezhengshiqi** [comment]
@HackDark00 It has already been disabled in config by injecting `disable-external-gpu` property.

**Comment by HackDark00** [comment]
Sorry I hadn't seen it before, then I don't understand why the battery draining so fast... with ubuntu i can reach about 9 hours

**Comment by stevezhengshiqi** [comment]
You can discuss the battery issue in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/224

My guess is that the unworking Intel wireless card consumes power, and macOS doesn't provide the FrequencyVector plist for KabyLake-R in X86PluginFamily.kext

**Comment by Menchen** [comment]
I think it's because 
- HiDPI(more pixel to render= higher graphic power, and more memory for framebuffer, like 1~2 W more than default)
- Background apps/service
- Non-perfect CPU/iGPU power management/driver(faked)?
- Linux is optimized and not that battery consuming (A fresh Linux install without any optimization is about 4~5h of battery life, but you can use powertop by intel to optimize it).
- Intel Wifi is still consuming power even we can't use it.
I would say that mainly is because in macOS apps aren't really close when you quit it.
Undelvolt may help you save like half-hour to an hour.

**Comment by HackDark00** [comment]
Thanks for the answers!
