### ISSUE TITLE
Dualboot on one SSD

### ISSUE THREAD

**Issue by ltfysl** [daliansky/XiaoMi-Pro-Hackintosh#228]
Is it possible to dualboot hackintosh and Windows on one drive? 
My second Slot is used for the internal wificard so I have only one Slot .
Any Tutorials there ?

**Comment by Alkanna** [comment]
It is absolutely possible, just partition your drive properly. Keep a partition as NTFS and the other as APFS and you're good to go.
Keep in mind windows and macos bootloaders don't play well together and on windows updates windows might add a file to the EFI that you need to remove in order to get into Clover again.
