### ISSUE TITLE
Kernel panic on Catalina beta 5

### ISSUE THREAD

**Issue by Alkanna** [daliansky/XiaoMi-Pro-Hackintosh#229]
Tried to update to beta 5 but I'm having a kernel panic sadly.

Hitting a few errors before the panic aswell :

AppleMUController::smcReadKey Error: received error 0x04 when reading key 'MSLD'

Getting the same error for keys ALRV and ALV0 as well.

Panic says :

Unsupported GraphicsSchedulerSelect=2\n"0skl/IntelAcelerator.cpp:2070

I tried using OpenCore instead of Clover but I couldn't make it verbose, and it seems to kernel panic too.

I can get into single user mode though.

**Comment by stevezhengshiqi** [comment]
The error `AppleMUController::smcReadKey Error: received error 0x04 when reading key 'MSLD'` can be ignored. It is caused by `SSDT-ALS0`.

I think you need a fresh update of the latest EFI. I have no problem updating to beta 5 and enabling HiDPI.
<img width="610" alt="Screen Shot 2019-07-16 at 10 49 19 PM" src="https://user-images.githubusercontent.com/36894554/62413701-f092d580-b5df-11e9-8521-f7b03f79751a.png">

**Comment by Alkanna** [comment]
Hmm, I am using a fresh update and I have no kexts installed on the system itself, it's all injected.

**Comment by stevezhengshiqi** [comment]
You need to re-check your EFI folder, especially if you have two EFI partitions.
BTW, it's a user-configuration problem. I am sure the EFI is good.

**Comment by Alkanna** [comment]
I reinstalled catalina from the recovery partition, removed almost everything from the /S/L/E folder via single user mode and used a clean EFI from your repo, and it indeed works.
The issue must have been on my end, sorry for bothering.
