### ISSUE TITLE
PM981 Issue

### ISSUE THREAD

**Issue by digitxo** [daliansky/XiaoMi-Pro-Hackintosh#231]
Hi sorry, I don't have a Xiami But I see this Laptop uses a a PM981 - I need help to make my PM981 work on an DELL XPS 13 9370. Please the person who coded this git repository message me here so I can be helped. I will give you my CLOVER file if this is what you need to see.

**Comment by stevezhengshiqi** [comment]
@digitxo Hi, actually there're no perfect solutions for PM981. It's better to switch to an alternative disk; otherwise, you may suffer from frequent KPs.

If you still want to use PM981, you can try https://www.tonymacx86.com/threads/how-to-fix-pm981-in-10-13-3-17d47.245063
Personally, I agree with what Rehabman has said, 
![屏幕快照 2019-08-06 01 13 20](https://user-images.githubusercontent.com/36894554/62512783-67e68600-b7e7-11e9-807f-30751d38feaf.jpg)

**Comment by OneSecure** [comment]
maybe here is a solve. https://download.csdn.net/download/caochenhins/11159007
