### ISSUE TITLE
fingerprint scanner can now host BCM Bluetooth

### ISSUE THREAD

**Issue by radmanz** [daliansky/XiaoMi-Pro-Hackintosh#246]
hey @stevezhengshiqi 
I've made some progress with the GTX version of the XiaoMi Notebook pro that does not have the WLAN_LTE M.2 socket pins available on the PCB. I couldnt find any other solution that didnt involve losing my Camera functionalliy within OSX which is the current work around when using this BCM M.2 package from this [taobao listing](https://item.taobao.com/item.htm?id=532197802538&sku=5919063:3266781&sku=5919063:3266781).  

As the ELAN Fingerprint sensor will never be used i managed to trace the D+- pins from this connector to a safe place to solder the USB data lines (D280) succesfully.

I have attached photos showing the successful connection and operation, along with a new SSDT that disables the INTEL BT and enables the ELAN USB Port to allow for the BCM BT to become active within the environment. Please note my new BT antenna location, which has no interference from the trackpad sheilding and should increase reliablity.

[SSDT-USB-FingerBT.aml.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3536925/SSDT-USB-FingerBT.aml.zip)

![BCM](https://user-images.githubusercontent.com/5206240/63633110-24a86600-c675-11e9-9c40-22d541421933.png)
![PCB_solder_points](https://user-images.githubusercontent.com/5206240/63633111-24a86600-c675-11e9-9b12-508d692e3600.png)
![Trackpad_antenna_AP](https://user-images.githubusercontent.com/5206240/63633112-2540fc80-c675-11e9-9cd3-253f40dc7abe.png)
![Screen Shot 2019-08-24 at 1 44 06 pm](https://user-images.githubusercontent.com/5206240/63633121-46095200-c675-11e9-9012-df6e7f73fb59.png)

**Comment by stevezhengshiqi** [comment]
@radmanz Thank you for your efforts! That's a great news to GTX model users who want to use their wireless cards' BT function.

Just a suggestion, In your SSDT-USB-FingerBT, HS02 can be deleted since it's for WLAN_LTE slot. Could you test with the following SSDT? If it's ok, I will submit it on this repository.
[SSDT-USB-Fingerprint.aml.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/3537398/SSDT-USB-Fingerprint.aml.zip)

**Comment by radmanz** [comment]
Tested the above SSDT, confirmed as working 👍
thanks @stevezhengshiqi

**Comment by Recreabox** [comment]
Good job ! 
I have bought the same wdxxfu adapter from taobao.
I have connected the wifi card successfully today but i don't see the soldering bluetooth so this week i will try your version with the fingerprint sensor. It will be easier to solder i think lol

Just a noob question : When you ask to replace the "SSDT-USB.aml"  by "SSDT-USB-Finger.aml", are we supposed to rename the new in "SSDT-USB.aml"  ?

**Comment by Menchen** [comment]
> Good job !
> I have bought the same wdxxfu adapter from taobao.
> I have connected the wifi card successfully today but i don't see the soldering bluetooth so this week i will try your version with the fingerprint sensor. It will be easier to solder i think lol
> 
> Just a noob question : When you ask to replace the "SSDT-USB.aml" by "SSDT-USB-Finger.aml", are we supposed to rename the new in "SSDT-USB.aml" ?

- It's the latter case, you delete the original one and rename the new one.
   
   
   
   
Btw, I still couldn't get Bluetooth working, so I'm thinking to replace it with the camera, so:

- Can someone show me how the camera connector is and if it's easy to get one without Taobao?

- And if a normal USB Bluetooth dongle can enable handoff/continuity without external kext?

**Comment by radmanz** [comment]
hey @Menchen , I will start from the basics here to help resolve the issue.
1. Ensure the finger print flex cable is disconnected as defined in the photos above,
2. There are a few ways to debug the bluetooths connection to the motherboard, its a bit strange that its not working OOB with the latest fingerprint AML file. One way to check your soldering connection is to boot a live linux distro from the USB and run 'lsusb' from the terminal, this will show you all the connected devices to your USB bus. 
You **should not** see a device called '04f3:0c1a - Elan microelectronics', you should see a device called '05ac:8290 - Apple Inc' which is the Apple BT adaptor.
If you see the Apple Inc BT adaptor, then the AML file is not loaded properly? Let me know how you go with further debugging.  I have attached a before and after shot of the 'lsusb' command in linux showing a successful mounting of the BT device on the USB bus as device 4.
<img width="808" alt="Screen Shot 2019-09-15 at 12 40 40 pm" src="https://user-images.githubusercontent.com/5206240/64916754-44373800-d7b6-11e9-9a91-8ea7440c70b2.png">


Can you post some photos of your WiFi card PCB and the solder connection to D280?

**Comment by radmanz** [comment]
hey @Recreabox , 
when you run the installer in this repository, there is a bash menu which will automoate the installation of that AML file for you. the commit for this option can be found here.. 
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/7a272d0cc20123266f6b0be1b0386adb8199a856
clone the repo and run install.sh after installing OSX.

**Comment by Menchen** [comment]
@radmanz Thanks for your help! My issue is not by using fingerprint scanner to replace Bluetooth.

My model is MX150 and have WLAN_LTE port, you can see the picture in #101 . The weird thing is that it's not recognized even in Linux. After resoldering 2 more times and still without luck.

Do you think that's possible that I broke WLAN_LTE USB line by bad soldering/bridging? Because the last attempt I tried I checked that pin 4 and pin 6 is shorted(already soldered in and checked with pin 6 and D+ pad in the adaptor).

**Comment by Recreabox** [comment]
@Menchen
I am in the same situation 
So I think it will be easier to solder on the fingerprint

**Comment by Menchen** [comment]
@Recreabox  I mean, with my soldering skill I would probably ruin it.. so I don't think I would risk it.

**Comment by Menchen** [comment]
Someone may be interested in #262

**Comment by radmanz** [comment]
hey @Menchen and @Recreabox , it sounds like there is a serious issue with the pads on these boards and they have more than 8 layers which can cause issues if you have your soldering iron turned up too hot (can burn through layers). can u test the short when its unplugged from the BT adaptor board? this may be causing the short and not your WLAN_LTE port. 
Else, if you still get a short circuit while the cable is unplugged from the adaptor board then you're most likely out of luck. I recommend changing to the fingerprint solution as the solder pads are a lot easier to solder too, keep the soldering iron around 300C for these boards, use plenty of flux and dont drink a tonn of coffee before attempting :D

**Comment by Menchen** [comment]
I mean, I don't feel comfortable soldering near plastic(last one didn't go well, I was soldering pinout for a nfc module, and after a whilr I found out that the plastic have melted a bit and bent.... 😂 ). So I think I will stick to either replace camera(need that cable, maybe I can find one without taobao), use a usb bt, or use vm to drive intel bt...

Or just bt adaptor is broken, (I doubt it) but thanks anyway for your help.

**Comment by nobitanobi** [comment]
@radmanz, @stevezhengshiqi

I found a D280 on my TM1701. There were traces going from it to the FP connector, so i figured those had to be the D+- pins.
They were much easier to solder than the tiny WLAN_LTE M.2 pins:
![IMG_8458](https://user-images.githubusercontent.com/1553458/64948531-e08e3700-d8a9-11e9-8809-ec8a0e0b08c0.jpg)

Bluetooth works now, with continuity and all.

Thanks are bunch guys!

**Comment by Recreabox** [comment]
@radmanz 
So i decided to test with D280 because WLAN doesn't worked for me

I use Ubuntu to test the solder
It's recognized ! :)

![IMG_5436](https://user-images.githubusercontent.com/47223322/64976252-1be03400-d8b1-11e9-8620-53e5ceb18206.jpg)

But how to know if it's succesfully recognized on MacOS ?
Cause before use the wdxxfu card, i activated the intel bluetooth by the VM Ware method.

I have replaced the SSDT-USB with the SSDT-USB-Fingerprint in this thread and rename it in SSDT-USB but i think it's not activated on MacOS

**Comment by hele204** [comment]
@Menchen @stevezhengshiqi @nobitanobi @radmanz 
Thank you for your reminder.I tried to use fingerprint scanner to host BCM Bluetooth and succeeded, and my welding did not damage the motherboard, because I bought a 6PIN soft wire from Taobao and then welded it directly from the other end of the soft wire. Now my Bluetooth and WiFi work perfectly.
![64948531-e08e3700-d8a9-11e9-8809-ec8a0e0b08c0](https://user-images.githubusercontent.com/28864419/65095965-da0cd600-d9f5-11e9-88fb-b8013e9f09b1.jpg)
![QQ20190918-0](https://user-images.githubusercontent.com/28864419/65095966-da0cd600-d9f5-11e9-9eb9-04c24f99a082.jpg)
![c4d146db39aece](https://user-images.githubusercontent.com/28864419/65095967-da0cd600-d9f5-11e9-87cb-8650de5b0c9c.jpg)

**Comment by hele204** [comment]
@stevezhengshiqi @radmanz @Menchen @nobitanobi 
Thank you for your reminder.I tried to use fingerprint scanner to host BCM Bluetooth and succeeded, and my welding did not damage the motherboard, because I bought a 6PIN soft wire from Taobao and then welded it directly from the other end of the soft wire. Now my Bluetooth and WiFi work perfectly.


![c4d146db39aece](https://user-images.githubusercontent.com/28864419/65096341-37eded80-d9f7-11e9-8709-7a50b9ec3a2e.jpg)
![QQ20190918-0](https://user-images.githubusercontent.com/28864419/65096342-37eded80-d9f7-11e9-8518-947765b7d437.jpg)
![QQ20190918-092825](https://user-images.githubusercontent.com/28864419/65096343-38868400-d9f7-11e9-848b-e9b888ecaf86.png)

**Comment by Recreabox** [comment]
I got Wi-Fi and Bluetooth working fine.
It's better to use the fingerprint scanner cause it's lot of easier to solder

**Comment by zb2947244682** [comment]
too hard core，made my head painful！（过于硬核，使我头疼）

**Comment by stevenzzc** [comment]
> @stevezhengshiqi @radmanz @Menchen @nobitanobi
> Thank you for your reminder.I tried to use fingerprint scanner to host BCM Bluetooth and succeeded, and my welding did not damage the motherboard, because I bought a 6PIN soft wire from Taobao and then welded it directly from the other end of the soft wire. Now my Bluetooth and WiFi work perfectly.
> 
> ![c4d146db39aece](https://user-images.githubusercontent.com/28864419/65096341-37eded80-d9f7-11e9-8709-7a50b9ec3a2e.jpg)
> ![QQ20190918-0](https://user-images.githubusercontent.com/28864419/65096342-37eded80-d9f7-11e9-8518-947765b7d437.jpg)
> ![QQ20190918-092825](https://user-images.githubusercontent.com/28864419/65096343-38868400-d9f7-11e9-848b-e9b888ecaf86.png)




Hello, can you give me the 6pin Taobao link? I couldnt find it.
Thanks

**Comment by hele204** [comment]
> > @stevezhengshiqi @radmanz @Menchen @nobitanobi
> > Thank you for your reminder.I tried to use fingerprint scanner to host BCM Bluetooth and succeeded, and my welding did not damage the motherboard, because I bought a 6PIN soft wire from Taobao and then welded it directly from the other end of the soft wire. Now my Bluetooth and WiFi work perfectly.
> > ![c4d146db39aece](https://user-images.githubusercontent.com/28864419/65096341-37eded80-d9f7-11e9-8709-7a50b9ec3a2e.jpg)
> > ![QQ20190918-0](https://user-images.githubusercontent.com/28864419/65096342-37eded80-d9f7-11e9-8518-947765b7d437.jpg)
> > ![QQ20190918-092825](https://user-images.githubusercontent.com/28864419/65096343-38868400-d9f7-11e9-848b-e9b888ecaf86.png)
> 
> Hello, can you give me the 6pin Taobao link? I couldnt find it.
> Thanks

https://item.taobao.com/item.htm?spm=a230r.1.14.118.2a9a2871m7DWBl&id=598728876017&ns=1&abbucket=18#detail

here you go

**Comment by stevenzzc** [comment]
> > > @stevezhengshiqi @radmanz @Menchen @nobitanobi
> > > Thank you for your reminder.I tried to use fingerprint scanner to host BCM Bluetooth and succeeded, and my welding did not damage the motherboard, because I bought a 6PIN soft wire from Taobao and then welded it directly from the other end of the soft wire. Now my Bluetooth and WiFi work perfectly.
> > > ![c4d146db39aece](https://user-images.githubusercontent.com/28864419/65096341-37eded80-d9f7-11e9-8709-7a50b9ec3a2e.jpg)
> > > ![QQ20190918-0](https://user-images.githubusercontent.com/28864419/65096342-37eded80-d9f7-11e9-8518-947765b7d437.jpg)
> > > ![QQ20190918-092825](https://user-images.githubusercontent.com/28864419/65096343-38868400-d9f7-11e9-848b-e9b888ecaf86.png)
> > 
> > 
> > Hello, can you give me the 6pin Taobao link? I couldnt find it.
> > Thanks
> 
> https://item.taobao.com/item.htm?spm=a230r.1.14.118.2a9a2871m7DWBl&id=598728876017&ns=1&abbucket=18#detail
> 
> here you go

thank you so much
