### ISSUE TITLE
Updating to Catalina?!

### ISSUE THREAD

**Issue by Chazy12** [daliansky/XiaoMi-Pro-Hackintosh#291]
Hello.
I have a daily driver daliansky hackintosh on mi notebook pro.
Now I would love to upgrade to calatina.
If it's possible, I would like to know the step for upgrading.
E.g. the efi must be updated before or after the o.s. upgrade?!
My USB Bluetooth and wifi dongle, will work?!
There's any issue with Catalina?
Thanks a lot 🙏

**Comment by stevezhengshiqi** [comment]
> If it's possible, I would like to know the step for upgrading.
E.g. the efi must be updated before or after the o.s. upgrade?!

Yes, you need to update EFI every time before a major system update. 

> My USB Bluetooth and wifi dongle, will work?!

https://github.com/chris1111/Wireless-USB-Adapter-Clover
https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/

> There's any issue with Catalina?

It depends on your setup. No support for 32 bit software.

I will close this issue because it's not an EFI issue or development suggestion. Issues like https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/290 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/273 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/290 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/286 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/274 https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/269 have already covered this issue.
