### ISSUE TITLE
RDM Video playback

### ISSUE THREAD

**Issue by Mateo1234454545** [daliansky/XiaoMi-Pro-Hackintosh#310]
Is there anyway to play netflix via safari or videos from appe tv+ app?
Both show trailers but when I try to play the movie I get blank screen.

**Comment by stevezhengshiqi** [comment]
According to https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Shiki.en.md#general-faq  

> Can I play HTML5 Netflix videos with Shiki?
No, you cannot since Netflix limited their 1080p content for very few mac models even excluding most Mac Pros.

so our hackintoshes may not support Netflix.

Same issue https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/237

**Comment by stevezhengshiqi** [comment]
Not sure on videos from appe tv+ app, but it’s a WhateverGreen problem. Nothing can be done in this repository.

**Comment by johnnync13** [comment]
This need reverse engineering to extract keys for drm like amd gpu desktop that support netflix and more
