### ISSUE TITLE
Problems with full screen videos of any type

### ISSUE THREAD

**Issue by Cuccheis** [daliansky/XiaoMi-Pro-Hackintosh#332]
Dear to all,
Im having issues with full screen videos of any type, from youtube to VLC.
No issues in game like PTCGO full screen and it works perfectly ..
Any are having this issue? Any advice to solve? 
Thanks a lot
Andrea

**Comment by linkerGitHub** [comment]
according to #324 
you can try to close the hardware accelarate option of chrome to avoid the problem that screen shining...and I dont sure this is your issue

**Comment by stevezhengshiqi** [comment]
Hi, the description of this issue is so vague. Please describe specifically what does it mean by "having issues", such as glitches, or kernel panic.

A screenshot may help to diagnosis this issue. Also, you may find helpful resources on https://github.com/acidanthera/WhateverGreen, the video driver of this EFI.

**Comment by msr1715** [comment]
> according to #324
> you can try to close the hardware accelarate option of chrome to avoid the problem that screen shining...and I dont sure this is your issue

I doubt it, he claims that he is having issues with VLC too

**Comment by Cuccheis** [comment]
Hello guys thanks for the reply :)
I solved all issues changing the HDMI cable and disabling the hw accelerate option in chrome.
I think the hdmi cable had a lot of time .. maybe 5+ years :D 
Now its perfect. Will try with an USB C to HDMI cable! 

Andrea
