### ISSUE TITLE
Kernel panic after Catalina beta 10.15.4

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#340]
Hello, I have a big problem.
after installing Catalina Beta 10.15.4 my computer runs into kernel panic and doesn't boot.

Is there a way to boot into recovery mode or similar?

I read in an article that from 10.15.4 apple will block kext extensions, is it true?

Thanks

**Comment by matvada** [comment]
Finally i make the computer start by selecting "inject EFI extensions" into clover booting options but now i have a lot graphical issues (ex. animations are buggy, the Launchpad opens very slow). I attach my kernel panic report.

[Kernel panic 10.15.4 beta 1.txt](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4241858/Kernel.panic.10.15.4.beta.1.txt)

**Comment by matvada** [comment]
Sorry "Inject EFI strings" not EFI extensions. And another bug is that the audio doesn't work anymore.

**Comment by Menchen** [comment]
Try booting from clean EFI....

**Comment by matvada** [comment]
@Menchen thanks for your reply,

I mounted EFI, deleted CLOVER and BOOT folder and replaced with the last release from this repo but the problem still persists.

**Comment by Menchen** [comment]
You can try to roll back to the version before updating using recovery... try `F1` in clover menu...

**Comment by matvada** [comment]
Unfortunately i can't rollback to a previous version because it rolls back to the same 10.15.4 beta 1.

I suppose that 10.15.4 breaks something into EFI. 

Main issues are on graphic and sound.

**Comment by stevezhengshiqi** [comment]
@matvada Hi, you need to compile the latest WhateverGreen to support macOS10.15.4. The commit https://github.com/acidanthera/WhateverGreen/commit/e53252dec5c443c53231ddd1b50b2ee1491caf41 should fix the KP.

**Comment by matvada** [comment]
@stevezhengshiqi i'm sorry but i'm not so skilled, i don't know how to compile WhateverGreen...

**Comment by johnnync13** [comment]
@matvada witch hackintool or https://github.com/corpnewt/Lilu-and-Friends it’s easy

**Comment by johnnync13** [comment]
@matvada 
[AppleALC-1.4.7-2020-02-24 10.57.08.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243941/AppleALC-1.4.7-2020-02-24.10.57.08.zip)
[CPUFriend-1.2.0-2020-02-24 10.57.13.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243942/CPUFriend-1.2.0-2020-02-24.10.57.13.zip)
[HibernationFixup-1.3.2-2020-02-24 10.57.17.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243943/HibernationFixup-1.3.2-2020-02-24.10.57.17.zip)
[Lilu-1.4.2-2020-02-24 10.57.24.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243944/Lilu-1.4.2-2020-02-24.10.57.24.zip)
[NVMeFix-1.0.1-2020-02-24 10.57.28.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243945/NVMeFix-1.0.1-2020-02-24.10.57.28.zip)
[VirtualSMC (All Tools)-1.1.1-2020-02-24 10.57.53.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243946/VirtualSMC.All.Tools.-1.1.1-2020-02-24.10.57.53.zip)
[WhateverGreen-1.3.7-2020-02-24 10.58.32.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/4243947/WhateverGreen-1.3.7-2020-02-24.10.58.32.zip)

**Comment by matvada** [comment]
@johnnync13 thank you very much! i used hackintool and now all works like a charm.
Do you think that will be safe if i update all the other kext?


![Schermata 2020-02-24 alle 11 10 55](https://user-images.githubusercontent.com/52761699/75144026-7601e280-56f6-11ea-9e7e-94e7ca8d0236.png)

At this time i have installed the versions included in the latest release of this repo.
Thanks

**Comment by stevezhengshiqi** [comment]
BTW, you need to know all these stuff before trying a beta macOS version.

**Comment by matvada** [comment]
@stevezhengshiqi i have never had problems like this before, i'm an Apple beta tester since Snow Leopard, is the combination of Mac OS beta with hackintosh that caught me unprepared ;)

BTW, i think this issue can help someone else who may be in the same situation.

**Comment by arandax** [comment]
how can I Inject EFI strings to boot again?

**Comment by matvada** [comment]
@arandax thanks to @johnnync13 you don't need to use hackintool, simply mount EFI and replace the WhateverGreen kext with the one (1.3.7) from the comment above.

https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/340#issuecomment-590243992

**Comment by arandax** [comment]
Thanks! It's better to update other kext too?

**Comment by matvada** [comment]
@arandax i updated other kext without problems.

**Comment by markl17** [comment]
how did you get out of that kp to finish the 10.15.4 install  here is syslog
Process:               PAH_Extension [502]
Path:                  /System/Library/Input Methods/PressAndHold.app/Contents/PlugIns/PAH_Extension.appex/Contents/MacOS/PAH_Extension
Identifier:            com.apple.PressAndHold
Version:               1.3 (57)
Build Info:            PressAndHold-57000000000000~5
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           PAH_Extension [502]
User ID:               501

Date/Time:             2020-03-22 19:29:04.961 -0400
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12
Anonymous UUID:        E7586763-93A7-54D2-E96C-93D91A4C1858


Time Awake Since Boot: 59 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [502]

Application Specific Information:
dyld3 mode
Configuration error: Couldn't retrieve XPCService identifier from service bundle.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libxpc.dylib                  	0x00007fff713ffc79 _xpc_copy_xpcservice_identifier.cold.1 + 14
1   libxpc.dylib                  	0x00007fff713e84e7 _xpc_copy_xpcservice_identifier + 106
2   libxpc.dylib                  	0x00007fff713f6b60 xpc_handle_subservice + 45
3   com.apple.ViewBridge          	0x00007fff6c4f335d +[NSViewService_PKSubsystem _initForPlugInKit] + 292
4   com.apple.ViewBridge          	0x00007fff6c4f339c +[NSViewService_PKSubsystem initForPlugInKit] + 19
5   com.apple.pluginkit.framework 	0x00007fff63dcf06a __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_INIT__ + 88
6   com.apple.pluginkit.framework 	0x00007fff63dd82ab 0x7fff63dbe000 + 107179
7   com.apple.pluginkit.framework 	0x00007fff63dd7ae3 0x7fff63dbe000 + 105187
8   com.apple.pluginkit.framework 	0x00007fff63dd700d 0x7fff63dbe000 + 102413
9   com.apple.pluginkit.framework 	0x00007fff63dd6cc9 0x7fff63dbe000 + 101577
10  com.apple.pluginkit.framework 	0x00007fff63dd6b38 0x7fff63dbe000 + 101176
11  com.apple.pluginkit.framework 	0x00007fff63dd71f6 0x7fff63dbe000 + 102902
12  com.apple.Foundation          	0x00007fff3c8f237c NSExtensionMain + 49
13  libdyld.dylib                 	0x00007fff71199405 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff713a25b4 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff713a25b4 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff713a25b4 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000600  rbx: 0x000000010bf64440  rcx: 0x00007fff714042cd  rdx: 0x00000000ae643024
  rdi: 0x0000000000000000  rsi: 0x0000000000000600  rbp: 0x00007ffee3e76580  rsp: 0x00007ffee3e76568
   r8: 0x00000000000000a9   r9: 0x00000000000007fb  r10: 0x0000000000000d20  r11: 0x0000000000000060
  r12: 0x00007fff6c58252b  r13: 0x00007fff9d7fb560  r14: 0x00007fff6c4cf36a  r15: 0x00007fff3ca55a2b
  rip: 0x00007fff713ffc79  rfl: 0x0000000000010246  cr2: 0x00007fff38f64203
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

**Comment by markl17** [comment]
none of those kexts won't help unless you get those efi files one in clover and one in boot available at insanelymac no where else 
https://www.insanelymac.com/forum/topic/342444-pre-release-macos-catalina-10154/?page=10&tab=comments#comment-2713474

**Comment by arandax** [comment]
The fix provided above was for the previous beta update (10.15.4 beta 5).
The fix you provided worked for beta 6, but now I lost the windows logo at boot, any suggestion? I got a black and yellow "maintenance" image instead.

**Comment by stevezhengshiqi** [comment]
@matvada Hi, I am not sure what do you mean by the 

> black and yellow "maintenance" image instead.

If you have the same problem as https://github.com/CloverHackyColor/CloverBootloader/issues/89 mentions, you need to downgrade Clover version to r5104.

**Comment by klich3** [comment]
for panic kernel you have solution on this link -> [](https://github.com/klich3/opencore-0.6.0-asus-p8z68-deluxe)

regards
