### ISSUE TITLE
freeze during installation

### ISSUE THREAD

**Issue by macca0612** [daliansky/XiaoMi-Pro-Hackintosh#381]
Hi, i have a problem during installation procedure, i have followed the procedure written in "Xiaomi Mi Notebook Pro MacOS Catalina Installation Guide || ENGLISH", downloaded the last Catalina (19E287), used Balena Etcher to create USB drive, i put it in the Xiaomi eresed the SSD, click Install, the system rebooted, i select the new boot option, appears apple logo, the loading line, and "About 13 minutes reamining..." and stop here, i have tried to wait, about 1hr, but nothing change.

how can solve it ?

Thank you very much

**Comment by Menchen** [comment]
ssd model?

**Comment by macca0612** [comment]
@Menchen i used the SSD of the Xiaomi mi notebook pro

**Comment by Menchen** [comment]
And what model is that?(there’s 2 version)

**Comment by macca0612** [comment]
@Menchen is Samsung MZVLB256HAHQ-0000

**Comment by Menchen** [comment]
You need to change your ssd.

**Comment by macca0612** [comment]
@Menchen Ah ok thanks, which SSD should i take ?
an SSD like Crucial MX500 CT500MX500SSD4 or WD BLUE WDS500G2B0B should be work ?
or can you suggest me a 500gb low price SSD
thank you very much

**Comment by Menchen** [comment]
No idea about crucial or WD, I use Samsung 970 evo. With different firmware version across the same ssd it’s hard to recommend. Some people have issue with 970 even though I and more have the same one and it run flawlessly.

**Comment by MarFre22** [comment]
> No idea about crucial or WD, I use Samsung 970 evo. With different firmware version across the same ssd it’s hard to recommend. Some people have issue with 970 even though I and more have the same one and it run flawlessly.

Also I have been using 970 evo without any huge problems, but at benchmark it only has more or less 2400 MB/s Write and 2800 MB/s Read. Compared with Windows it has +-3400/3500MB/s read and 2400/2500MB/s Write. I don't know why this happens with MacOs.
Is it something related with a specific firmware?

**Comment by MarFre22** [comment]
> @Menchen Ah ok thanks, which SSD should i take ?
> an SSD like Crucial MX500 CT500MX500SSD4 or WD BLUE WDS500G2B0B should be work ?
> or can you suggest me a 500gb low price SSD
> thank you very much

I had a WD 500gb SATA with MacOS, after one year it died without any explanation... I think it corrupt the firmware I don’t know why.

Some time ago, I found some information about SSD's, only NVMe.
I think that newer MacOS versions aren't 100% prepared for SATA SSDs, because I felt (with Mojave) some times it throttles with some data multitasking (including MacOS data alocation, e.g. installing large apps). Also, I think, older MacBooks that officialy support newer MacOS versions have at least +-1000MB/s Read (Write?) SSDs.

Samsung 970 Evo is a beast, but, now, it’s a bit hard to find, consequently, a bit expensive. If you do not extremely need hight speed, I think Sabrent Rocket it's a good one.

Some photos of my search:
![SSD NVMe comparison 2020-02 Perfs price](https://user-images.githubusercontent.com/51057236/79753540-02530f00-830e-11ea-88b2-ac4c26e11802.png)
![SSD NVMe comparison 2020-02 Power Efficiency](https://user-images.githubusercontent.com/51057236/79753571-1139c180-830e-11ea-8cb8-ffd9f608afd5.png)
![SSD NVMe comparison 2020-02 Power](https://user-images.githubusercontent.com/51057236/79753593-1991fc80-830e-11ea-8783-b3ec13bb48fc.png)
Credits to: gilles_polysoft and maxthackray from macrumors.com

**Comment by macca0612** [comment]
@MarFre22 thank you very much for these information, i will await a good offer
