### ISSUE TITLE
Brightness levels

### ISSUE THREAD

**Issue by influenist** [daliansky/XiaoMi-Pro-Hackintosh#421]
Hi, just got my hands on the NoteBook Pro 2017 / MX150 as working remote on 12.5" wasn't doable anymore since I started using 27" ^^

Anyways on topic. Referring to my NoteBook Air 12.5 I notice the brightness levels are off. Low brightness is hardly readable and maxed out I see a difference of +/- 10% in comparing with my 12.5. Shall I generate a SSDT-PNLF.aml to compare?

**Comment by stevezhengshiqi** [comment]
@influenist I don’t quite understand what your problem is. The lowest brightness level should be unvisible as what real Macs behave. Also, it’s normal that the max brightness level varies on different models. For Kabylake devices, we inject 0x56c UID in PNLF device. The SSDT-PNLF in this repository is from [Rehabman’s repository](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLF.dsl).
