### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by evandermends** [daliansky/XiaoMi-Pro-Hackintosh#443]
Could someone help with this kernel panic. I’m using clover boot. It happens after the Catalina os done installing and reboots.
![41B45279-1E4B-403D-82AF-C5AB464543CE](https://user-images.githubusercontent.com/68216998/88781941-88d48380-d17c-11ea-950b-6198d80213ef.jpeg)

**Comment by stevezhengshiqi** [comment]
Apparently, you are not using the EFI release from this repository.

**Comment by evandermends** [comment]
I used clover bootloader release

**Comment by stevezhengshiqi** [comment]
XiaoMi-Pro's EFI release never has boot arguments like -v keepsyms=1 that shown in your screenshot. Please re-check your EFI partitions in U-disk and SSD. When using XiaoMi-Pro EFI release, please delete `BOOT` and `CLOVER` folders and then copy them from the release pack.

Will close this issue since it's not related to the EFI release in the repository, and it's an installation problem. Please check the installation insturction links given in README.
