### ISSUE TITLE
Any chance to clean up this repo's info

### ISSUE THREAD

**Issue by muzafferdede** [daliansky/XiaoMi-Pro-Hackintosh#454]
I don't know why, some of the info seems to me wrong or miss targeted. Like for which device should follow which fix? Is there any outdated solution?

For example i have a mx150 Xiaomi Notebook Pro, i am not sure if should i just apply 15,4 smbios or apply one-key-cpufriend fix. I am not sure even do i need it or not. Do i need DVMT_and_0xE2_fix ?, i don't know. i just got lost a bit :)

Basically trying to find a way to clear which info is outdated, which info is a must do and which info is an optional depending on user's need. 

And maybe better to have a discussion section instead of having bunch of issues. So issues and discussions wont mess around.

**Comment by stevezhengshiqi** [comment]
I don’t find any outdated solution. The DVMT_and_0xE2_fix you mentioned is necessary when you want to connect to 4K monitor, which is described in https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Set-DVMT-to-64mb.

> if should i just apply 15,4 smbios or apply one-key-cpufriend fix.

As described in README, you can use one or another, which means both methods are OK. It really depends on user’s choice. By using one-key-cpufriend, you don’t have to change SMBIOS model, which is sometimes needed by users.

> Basically trying to find a way to clear which info is outdated, which info is a must do and which info is an optional depending on user's need.

As clearly written in README, DVMT_and_0xE2_fix and one-key-cpufriend both are in the Improvements section, which means they are all unnecessary except for specific reason.

There’re nothing users “must do” so far. Just delete boot and clover or oc folders and then copying new ones instead of replacing is necessary.

**Comment by muzafferdede** [comment]
i am so appreciated. Thanks for pointing out all my confused parts. I have spend a week on the docs already but yeah, those improvements make me think if i should apply them or am i good with the defaults. Thanks again.
