### ISSUE TITLE
Problem with CPU CPUFriendDataProvider and Geekbench score

### ISSUE THREAD

**Issue by alexmenn** [daliansky/XiaoMi-Pro-Hackintosh#53]
If I use XiaoMi NoteBook Pro EFI v1.2.3 with v1.2.2 CPUFriendDataProvider.kext and CPUFriend.kext (released on 13 May) instead of 1.2.3 (or 1.2.4) versions, geekbench is fine with 16.500 score in geekbench. 

Otherwise, if I use full clover folder (release 1.2.3 or 1.2.4), I just get 11.400 score in geekbench.

I think the updated release and CLOVER folder of @stevezhengshiqi has wrong CPUFriend kext, because I cant get good score. Anybody can check this?

**Comment by stevezhengshiqi** [comment]
Hi, I think it's a trade off between performance and power saving. If you prefer performance, you can try this `CPUFriendDataProvider.kext`. I set EPP at max performance level in this kext below. In the v1.2.2 EFI folder, the system doesn't enable HWP(SpeedShift) in Kabylake-R, resulting inefficient power management. 
[CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2270339/CPUFriendDataProvider.kext.zip)

**Comment by stevezhengshiqi** [comment]
Thanks for your test again. I tested for several frequencyvectors and found that the incorrect minimum frequency value can result in low mark in Geekbench. I used to set the minimum frequency to 400mhz, which is too low. I will update `CPUDataProvider` by using default apple min frequency value (1300mhz) in the near future.

**Comment by alexmenn** [comment]
Hi there again! I've tried your new release, and my geekbench is 16.200 with EPP and min freq 0.8ghz . Pretty good. With the kext you provided here, (max performance), I ger 17.100 score; but min freq es 1.3ghz (drain more battery I think). Is this ok?

**Comment by stevezhengshiqi** [comment]
Yeah, the purpose of the driver provided here is to enable higher performance. If you want a min freq 0.8ghz version of the kext above, here it is.
[CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2280357/CPUFriendDataProvider.kext.zip)

**Comment by alexmenn** [comment]
The CPUFriendProvider.kext you give me now is different than the new release one? Or is the same?

**Comment by stevezhengshiqi** [comment]
You said "I ger 17.100 score; but min freq es 1.3ghz (drain more battery I think)". So I modify the min freq value of the kext in the 2nd floor to meet your requirement.

**Comment by alexmenn** [comment]
Oh! Great! Now I get it. What differences are now with this new kext (updated to has min freq 0.8h) and the latest release one? Just the performance? I mean, battery life should be the same with both kexts?

**Comment by stevezhengshiqi** [comment]
Certainly we can't get both good performance and long battery life. The kext, which utilizes more aggressive frequency vector, in this issue are for people who want better performance, and kexts in my latest release provide balance battery life and performance.

**Comment by alexmenn** [comment]
Ok, then I will keep in balance mode. I prefer to lose 1000 in geekbench and win battery life!! Thank you

**Comment by chenjiangui** [comment]
1.6000是 i5 8250u跑的还是i7 8550u跑的? i5的话可以缩一下预算了

**Comment by stevezhengshiqi** [comment]
@chenjiangui i7跑的，多核分数i5会差一些，单核差不多。

**Comment by chenjiangui** [comment]
好的, 谢谢.
预算缩不了了, 内存是板载的

**Comment by sebmoris** [comment]
Hello guys,
I have a little problem, I have Mi i7 16gb and I can choose in clover MBP 15,2 but I must choose MBP 14,1 because in 15,2 my Macos don't boot.
I have actually latest EFI folder from stevezhengshiqi and macOS 10.13.6
sorry for my English ;)
thanks for help :)

**Comment by stevezhengshiqi** [comment]
@sebmoris There's no advantage to choose MBP 15,2. If you want better power management, please use `CPUFriendDataProvider` above.

By the way, MBP15,2 only supports 10.13.6 17G2112 and above. 17G65 doesn't support.

**Comment by sebmoris** [comment]
> @sebmoris There's no advantage to choose MBP 15,2. If you want better power management, please use `CPUFriendDataProvider` above.
> 
> By the way, MBP15,2 only supports 10.13.6 17G2112 and above. 17G65 doesn't support.

Thanks for help @stevezhengshiqi :)

**Comment by sebmoris** [comment]
thanks @stevezhengshiqi ,with CpuFriend above Mi book really work on 800Mhz :)
I have one question again ;)
I tried to use Turbo Boost Switicher, but this app can't off TB... 
Do I need to unlock the bios, just like I had to unlock for intel XTU in windows?

**Comment by sebmoris** [comment]
I will update to higher build :) so my last question is not actually :)
thx for help :)

**Comment by sebmoris** [comment]
last question ;)
What do you recommend to install? 
10.13.6 17G2208 macOS High Sierra or 18A389 macOS Mojave for better and more complete use of hardware in Xiaomi Mi Notebook Pro i7 8gen and 16gb ram ?

**Comment by sebmoris** [comment]
@stevezhengshiqi  I was able to install higher build of 10.13.6 and now I can choose in clover MBP 15,2 but trackpad don't work and is not detected
cpu and battery with your  CPUFriendDataProvider.kext on 800Mhz and disable bluetooth works fine :)
command :)

**Comment by stevezhengshiqi** [comment]
@sebmoris Congratulations. I still not recommend to choose MBP 15,2, the reason I have explained: there's no advantage to choose that. 

For the trackpad issue, you can try to run `sudo kextcache -i /` and restart, as said in `README.md - Installation`.

**Comment by sebmoris** [comment]
everything works fine but in my opinion on 10.13.6 MBP 15,2 some times in micro seconds I have some delays, for example in changing beetween users profiles, on startup login when I click on logo user to write pass and after write pass have to wait to load all desktop. So I update do Mojave and check performance, if in Mojave I see same problem, then I would be back to MBP 14,1 on 17G65 :)

**Comment by sebmoris** [comment]
ok I will back to MBP 14,1 on 17G65 because on Mojave Beta Public on 15,2 or 14,1 in Geekbench results was same 16600-16720 points, so it confirms what you wrote about choose MBP 15,2, so I wait to official Mojave, but still not have solution to Turbo Boost Switcher because I can't off TB with this tool... any ideas ? :)

**Comment by sebmoris** [comment]
hi guys :)
can you send the CPUFriendDataProvider.kext file on which you obtained the result 17100 on Geekbench? because actually on macOS Mojave on MPB15,2 my best results 16700 is only on Cpufrienddataprovider 800Mhz, on the other files the results are worse... ;/ should I return to MBP14,1 and repeat tests ??

**Comment by sebmoris** [comment]
I repeat test on MBP 14,1 and results same
How did you make 17100pts ;) ?

**Comment by lorenzoangotzi** [comment]
The power management should be right but I wanna know if it's possible mod it. Because when the pc reach 92 degrees at 45 watts the pc throttling and go back at 15w with lower frequency.
At 59/60 degrees there is so much space to increase the performance of the pc and have high frequencies.

I ran some test with all 3 CPUFriendDataProvider.kext.

With the one for Battery, the CPU never reach 45w and stay all the time at 15w. So lower performance:
![schermata 2018-09-26 alle 16 09 26](https://user-images.githubusercontent.com/17594880/46244284-ec54c500-c3dc-11e8-9ea6-648c75e18e5e.png)


With the one for Performance, the CPU stays at 45w for 11sec and go back at 15 for all the time. It never goes high.
![schermata 2018-09-26 alle 16 03 10](https://user-images.githubusercontent.com/17594880/46244263-98e27700-c3dc-11e8-981e-ae233a44237c.png)

with the one for Balanced, the CPU need 14/15sec before it reaches 90 degrees and goes back at 15w:
![schermata 2018-09-26 alle 16 36 31](https://user-images.githubusercontent.com/17594880/46244271-b0b9fb00-c3dc-11e8-96b7-942c5d9e9a9c.png)


Because it stays more time at 45w the CPUFriendDataProvider.kext for Balanced allow me to have a higher score in Cinebench than the one for Performance. This thing doesn't make any sense.

This CPU is made for stay at 15w but, because degrees are low, I wanna know if it's possible to let the CPU consume more watt and have high frequencies with more performance.

I think the problem here is because the pc cut down too much the watt for the CPU when it reaches 92 degrees. When it goes back at 15w and 60 degrees it should be able to increase again the wattage and frequencies.

**Comment by sebmoris** [comment]
@lorenzoangotzi  thanks so much for your test ;) I have same problem, we can not use the full power and frequency of the processor. next issue what I saw, its a better results on benchmarks with CPUFriendDataProvider.kext for better battery life than other files ;/

**Comment by lorenzoangotzi** [comment]
Any updates about my test? If you need I can make other tests.
I really hope that we can solve this problem

**Comment by chenjiangui** [comment]
我也发现这个问题了, 黑苹果下睿频时间不超过15S, 顶多就跑个GB4, 编译项目的时候频率一直是2.4GHZ, TDP 15W, 性能非常差, 有什么办法可以在OSX解锁低压U的TDP(PL1)吗? Linux下有人开源了Python写的一个脚本解锁低压U的TDP: https://github.com/erpalma/lenovo-throttling-fix

**Comment by alexmenn** [comment]
Hi @lorenzoangotzi @daliansky @stevezhengshiqi I "fix" this problem using older version of CPUFriendDataProvider.kext it. Months ago I could fix similar problem with HWP and score using kext in version 1.2.2 of @daliansky folder.

Try this kext, you will get more score when using geekbench and low freq is 0,74 or so, so is like balance mode.

now @daliansky  can try what is wrong with 1.2.8 kext, because it doesnt reach max score.

**Comment by stevezhengshiqi** [comment]
@alexmenn There's nothing wrong in v1.2.8's CPUFriendDataProvider. You should check your settings. A complete replace of v1.2.8 release is necessary if you keep getting low score. 

By the way, why are you keep @daliansky who is not responsible for the release after 1.0.0? He is busy so that I help him maintain this repository since April.

**Comment by alexmenn** [comment]
Hi @stevezhengshiqi You we're right. I copied full EFI folder but I don't know why, it didn't work. I downloaded it again, copy/paste, and now it works with good score. @lorenzoangotzi had the same problem, maybe he fixed it downloading again the EFI folder.
I thought you and daliansky were the same person. Sorry, I was wrong :)

Thank you for support! :)

**Comment by lorenzoangotzi** [comment]
> Hi @lorenzoangotzi @daliansky @stevezhengshiqi I "fix" this problem using older version of CPUFriendDataProvider.kext it. Months ago I could fix similar problem with HWP and score using kext in version 1.2.2 of @daliansky folder.
> 
> Try this kext, you will get more score when using geekbench and low freq is 0,74 or so, so is like balance mode.
> 
> I know this kext does not use HWP, maybe @daliansky can fix the new kext with HWP and good score results :)
> 
> now @daliansky can try what is wrong with 1.2.8 kext, because it doesnt reach max score.
> ![captura de pantalla 2018-10-29 a las 19 57 43](https://user-images.githubusercontent.com/42182041/47674097-caef2080-dbb6-11e8-837b-e60d9bdb07d5.png)
> ![captura de pantalla 2018-10-29 a las 20 01 06](https://user-images.githubusercontent.com/42182041/47674103-d04c6b00-dbb6-11e8-8c94-b9452461c522.png)
> [CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2526700/CPUFriendDataProvider.kext.zip)

The problem happens when you are in a real work with CPU at 100% and 92 degrees.
The turbo boost doesn't work anymore and goes down to 15w, 60 degrees and 2.3 GHz.

In the synthetic benchmark, you never reach 92 degrees so the CPU is always able to go at 45w and higher frequencies.

**Comment by lorenzoangotzi** [comment]
@alexmenn Yes, on Windows I'm able to stay at 45w watt, higher frequencies and degrees with so much more performance.
I have tried everything on MacOS. Nothing works.

**Comment by alexmenn** [comment]
Ok I see, it's a pitty. @stevezhengshiqi do you know how to fix it? or you have the same problem?

**Comment by alexmenn** [comment]
I mean, that if @lorenzoangotzi can use tdp at 45w for minutes on windows, why we cant do the same on mac. Is mojave problem? or we will find the same tdp problem in HS? Maybe in windows he can use tdp more time because he uses intel software to unrestrict the tdp!

**Comment by lorenzoangotzi** [comment]
@stevezhengshiqi On windows I can able to stay up to 45w for much longer than 28s.

On MacOs the CPU doesn't stay at 45w for 28s, but it stays at maximum wattage until it reaches 92 degrees than it drops frequencies, wattage and degrees at 60c without never going up.

It's a bit a miss, because at 60c there is so much room for having higher performance.

**Comment by Mateo1234454545** [comment]
CPUFriendDataProvider provided here for hwp is working only with smbios 14,1 ?
Cause I think 15,2 is closer to this laptop.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Hi, please read carefully the insturctions at the front. The CPUFriendDataProvider here are all exacted from MBP15,2.

**Comment by Mateo1234454545** [comment]
Yes , i reat that.
But when using mbp15,2 (without cpufriend and dataprovider) lower cpu freq is 1.2 , not 0.8 as with 14,1 and cpufriend.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 CPUFriend wil overwrite PM management of SMBIOS, so there's no point to change SMBIOS. 
 
I used the native PM template from MBP15,2 and modified the minimum frequency(from 1300 to 800) to generate the CPUFriendDataProvider provided above. Without CPUFriend*, the minimum frequency will be 1300mhz in MBP14,1 and also in MBP15,2 because it is designed by Apple.

Yes, we have hwp when using SMBIOS MBP15,2 or CPUFriendDataProvider above.
If you want to check the HWP status, you can use `AppleIntelInfo` and view the log.
[AppleIntelInfo.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2553348/AppleIntelInfo.kext.zip)

**Comment by Mateo1234454545** [comment]
[Terminal Saved Output.txt](https://github.com/daliansky/XiaoMi-Pro/files/2554741/Terminal.Saved.Output.txt)
How does it seem ?
Do I have proper cpu management ? Using smbios 15,2.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 You can see `IA32_PM_ENABLE...................(0x770) : 0x1 (HWP Supported and Enabled)` and `IA32_HWP_STATUS..................(0x777) : 0x0` in your log, which means HWP is opened successfully.

**Comment by Mateo1234454545** [comment]
Great.
So , why do you prefer smbios 14,1 over 15,2 ? Is there any problem with 15,2 ?

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Mainly there are three reasons. 
Firstly, which I mentioned many times, CPUFriend* will overwrite the origin PM of SMBIOS, so choose 14,1 or 15,2 won't affect PM.

Secondly, accroding to [info.plist](https://github.com/daliansky/XiaoMi-Pro/blob/master/EFI/CLOVER/kexts/Other/USBPorts.kext/Contents/Info.plist) in `USBPorts`, the USB configuration is model specific. Change in SMBIOS may cause unexpected USB error.

Thirdly, the EFI is purposely to support all system version from 10.13 to 10.14, and 10.13 can't boot with model MBP15,2.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Thank you for your help. If you use CPUFriendDataProvider in the top of this site, then your device is using MBP15,2’s battery management.

**Comment by lorenzoangotzi** [comment]
@stevezhengshiqi I have tried all the three CPUFriendDataProvider for the configuration with 14,1 and 15,2. Nothing change in the wattage use and there is the same drop of frequencies when reaches 92c degrees.

As you can see in my post of 29 Sept, the CPU doesn't stay at 45w for 28sec, but for 12sec with the kext for performance and 14sec for Balanced. This because it cut down everything every time at 92c.

**Comment by stevezhengshiqi** [comment]
@lorenzoangotzi I am only able to let macOS run MBP15,2's PM and modify minimum frequency, EPP, and maximum frequency. More specific modifications, like the temperature wall, are beyond my ability. We are using the native PM of MBP15,1 provided by Apple, so it may not fit for our CPU very well. 

By the way, I can generate a CPUFriendDataProvider with the minimum frequency 3.2GHz if you want high frequency. Not sure whether it will cause system error or not.

**Comment by Mateo1234454545** [comment]
Can you please make another one with min freq 1.2 and max freq 2.6 ? I think that would be nice for high temps and temp throttling.

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 Here it is. 
[CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2557354/CPUFriendDataProvider.kext.zip)

**Comment by Mateo1234454545** [comment]
Thanks , but not working. Max speed still 3.4
Is ot possible to have max speed at 3.4 when on power and 2.8 when on battery ?

**Comment by stevezhengshiqi** [comment]
@Mateo1234454545 It may be possible, but I don't know how.

**Comment by Mateo1234454545** [comment]
> @Mateo1234454545 Here it is.
> [CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoMi-Pro/files/2557354/CPUFriendDataProvider.kext.zip)

Is it possible to give it another try ? I'm using smbios 15,2 if this matters.

**Comment by wsadaaa** [comment]
我的cpu是i5 8265u，此处的三个CPUFriendDataProvider能用吗

**Comment by stevezhengshiqi** [comment]
@wsadaaa 可以的。

**Comment by aliyoge** [comment]
@stevezhengshiqi 请问我的电脑是Thinkpad E480 CPU是i5-8250U，请问可以用这个CPUFriendDataProvider吗？ 只需要把CPUFriend.kext和CPUFriendDataProvider.kext放到指定位置就可以了吗？还需要其他操作吗？

**Comment by stevezhengshiqi** [comment]
@aliyoge 首先要确保`plugintype=1`，X86PlugIn驱动未被修改。

推荐根据https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md 来自己生成CPUFriendDataProvider
