### ISSUE TITLE
Open core VS Clover ? Newbie is here 😎

### ISSUE THREAD

**Issue by MacUser341** [daliansky/XiaoMi-Pro-Hackintosh#544]
Hello
I have the Xioami notebook pro for a 3 years for now and I just found out that I can install Mac OSX on it - what a great job guys , so first of all thanks a lot for the hard work.
I have some questions and I hope it’s ok to ask .
1. In what way should I choose ? The clover one or the Open-Core one? What is the benefit of one on the other ? 
2. I’ve purchased a Mac compatible WiFi and BT card for perfection installation- this one : BCM943602CS[Card] (https://h5.m.taobao.com/awp/core/detail.htm?id=532197802538&ft=t&toSite=main)  , do I need to install something special for that card? Will it impact the WiFi and BT connection on the windows (I want to make a dual boot ) and what takes me straight to my third question 
3. What Operation system should I install first the windows 10 or the macOS  ? 
4. can I install the latest Mac OS version ?

Thanks

**Comment by stevezhengshiqi** [comment]
> In what way should I choose ? The clover one or the Open-Core one? What is the benefit of one on the other ?

The difference is very slight, and it really depends on users' preferences. If you have a great Clover theme, you might want to use Clover. You can read Clover and OpenCore section in README for basic understanding.

> I’ve purchased a Mac compatible WiFi and BT card for perfection installation- this one : BCM943602CS[Card] 

No need for driver on macOS, but you might need changes on BT side if you soldered it. Read [Work Around with Bluetooth](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Work-Around-with-Bluetooth). Windows drivers are provided at https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132#issuecomment-451629385 and https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/132#issuecomment-457301893.

> Will it impact the WiFi and BT connection on the windows 

It depends on how you deal with antennas.

> What Operation system should I install first the windows 10 or the macOS ?

Whatever, just make sure EFI partition is more than 200mb.

> can I install the latest Mac OS version ?

Yes, covered in README.

Please surf previous issues and better post questions on [Discussions](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/discussions) page instead of issue page.
