### ISSUE TITLE
config.plist problem in KBL Clover v1.5.9

### ISSUE THREAD

**Issue by segfault32** [daliansky/XiaoMi-Pro-Hackintosh#588]
I'm getting this warning during boot:

There is a problem in plist '\EFI\CLOVER\config.plist'
Warning: Custom has to be defined if Inject is defined in dict '/Graphics/EDID:290'.
Use CloverConfigPlistValidator or look in the log

I think the issue is related to this commit:
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/1a84eeee5b599f1a70abefedb3708801a65d9aa3

Inject for EDID got changed from false to true in CLOVER/config_kbl.plist

Is this a known problem?  

Thanks!

**Comment by stevezhengshiqi** [comment]
@segfault32 Thanks for pointing out. Yes, I intentionally did that because https://github.com/CloverHackyColor/CloverBootloader/commit/a0c543f100f2c962e785bdb4384b55f680280d87 should fix this warning. However, Clover published their release on a slow schedule, so we have to wait until r5139 is released to see that commit turn in effect.

**Comment by segfault32** [comment]
Got it!  Will patiently wait for the next release then.  :)
Thank you!
