### ISSUE TITLE
Update extensions

### ISSUE THREAD

**Issue by matvada** [daliansky/XiaoMi-Pro-Hackintosh#638]
Hello, I wanted to know if new releases are planned after version 1.6.4

**Second question:**
It's safe to update extensions by manually downloading them from Hackintool?
![Schermata 2022-03-14 alle 12 38 39](https://user-images.githubusercontent.com/52761699/158165102-48d938f9-49a0-4769-b69e-4621f6930949.png)

Thank you

**Comment by Menchen** [comment]
It's safe to update Kext by downloading it manually, but if what you want is upgrade your EFI(OpenCore) it's better to just run the `./makefile.sh` to generate the most latest release as it might bootloop due to `config.plist` update, and as always only mess with EFI if you have a backup and have a way to restore it.

**Comment by matvada** [comment]
@Menchen 
thank you for your answer.
I'll proceed with makefile.sh

Thanks!
