### ISSUE TITLE
Fans never run

### ISSUE THREAD

**Issue by Casm101** [daliansky/XiaoMi-Pro-Hackintosh#662]
Running MacOS Monterey 12.3.1 on the latest release of OpenCore on the repo, and I've noticed that the fans never run on my Xiaomi Mi Laptop Pro 16" (2020), even though the temps don't normally go above 65ºC.

Today I put the system under a synthetic load, 100% CPU usage at 70ºC sustained for about 5 minutes and the fans never came on, I also downloaded a fan controlling application (Macs Fan Control), but it does not recognise the system has any fans at all. 

It's possible that the fans are controlled only by BIOS, but even then, they should still run...

**Comment by stevezhengshiqi** [comment]
Just to make sure, your laptop is i5-10210U / i7-10510U, right? The fan is indeed controlled by BIOS, and we don't have many methods to control it. Since our DSDT does not have Embedded Control Field, we can't really determine the fan address and utilize https://github.com/acidanthera/VirtualSMC/blob/master/Docs/EmbeddedControllers.md

**Comment by Casm101** [comment]
Yeah, thats right, its the i7 10th gen.

If we can control it, the BIOS should at least be doing its own thing, no?

**Comment by stevezhengshiqi** [comment]
Yes, as far as I know. BIOS fan works fine, thought they may have a quite strategy under other OS.

**Comment by Casm101** [comment]
Fair enough then, I guess there's nothing to add to this, I'll check my BIOS fan profiles and mark the issue as closed.
